### ISSUE TITLE
Feature Request: Ignore certain SVN states

### ISSUE THREAD

**Issue by fleimgruber** [AurelienLourot/uncommitted#11]
I like the UNIX tradition of "nothing on stdout is good news", i.e. when all working
copies are clean, `uncommitted` gives no output.  Now what is considered "clean"?  There are some SVN repos containing locked files.  This might not really be an "unclean" state in the sense that there is no need for action as with modified / untracked files.

Consider a SVN repo that has locked files in it which turn up in the output as

```
D:\repo - Subversion
      K  path1\file1
      K  path1\file2
      K  path2\file1
...
```

this list can get quite big.  To be in line with behavior explained above, there should be no output since the
locking was already committed.  There could be a number of those states[1] which for one reason or another should not show up in the results (e.g. they are expected / need no action).

Thinking in terms of a solution, there could be an argument for ignoring certain svn states, e.g.

```
uncommitted --ignore-svn-states "KBT" .
```

what do you think?

[1] https://www.visualsvn.com/support/svnbook/ref/svn/c/status/

**Comment by AurelienLourot** [comment]
Sounds good @fleimgruber. I don't use SVN, so it might take a while before I pick this up. Feel free to implement it yourself and share, if you need it quick. I'll be happy to merge your work.

**Comment by AurelienLourot** [comment]
Closing as you've created a pull request upstream :)
https://github.com/brandon-rhodes/uncommitted/pull/22

**Comment by fleimgruber** [comment]
Yeah, also as per my last comment in https://github.com/AurelienLourot/uncommitted/pull/12.  Thanks again for your comments there.
